# Defines the following variables:
#   - MKL_CPARDISO_FOUND
#   - MKL_CPARDISO_LIBRARIES
#   - MKL_CPARDISO_INCLUDE_DIRS

if(NOT MKL_CPARDISO_DIR)
  set(MKL_CPARDISO_DIR /usr)
endif()

if(NOT MKL_LIBRARY_DIR)
  set(MKL_LIBRARY_DIR /usr/lib/x86_64-linux-gnu)
endif()

if(NOT MKL_MPI_WRAPPER_LIB)
  message(FATAL_ERROR "MKL CPardiso enabled but no MKL MPI Wrapper lib specified")
endif()

set(MKL_CPARDISO_LIBRARY_HINTS
  ${MKL_LIBRARY_DIR}
  ${MKL_CPARDISO_DIR}/lib/intel64
  ${MKL_CPARDISO_DIR}/lib)

find_path(MKL_CPARDISO_INCLUDE_DIR mkl_cluster_sparse_solver.h
  HINTS
    ${MKL_CPARDISO_DIR}/include/mkl
    ${MKL_CPARDISO_DIR}/include)

find_library(MKL_CPARDISO_LP64_LIBRARY NAMES mkl_intel_lp64 mkl_gf_lp64
  HINTS ${MKL_CPARDISO_LIBRARY_HINTS})
find_library(MKL_CPARDISO_SEQ_LIBRARY NAMES mkl_sequential
  HINTS ${MKL_CPARDISO_LIBRARY_HINTS})
find_library(MKL_CPARDISO_CORE_LIBRARY NAMES mkl_core
  HINTS ${MKL_CPARDISO_LIBRARY_HINTS})
find_library(MKL_CPARDISO_MPI_WRAPPER_LIBRARY NAMES ${MKL_MPI_WRAPPER_LIB}
  HINTS ${MKL_CPARDISO_LIBRARY_HINTS})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(MKL_CPARDISO DEFAULT_MSG
  MKL_CPARDISO_INCLUDE_DIR
  MKL_CPARDISO_LP64_LIBRARY
  MKL_CPARDISO_SEQ_LIBRARY
  MKL_CPARDISO_CORE_LIBRARY
  MKL_CPARDISO_MPI_WRAPPER_LIBRARY)

if(MKL_CPARDISO_FOUND)
  set(MKL_CPARDISO_INCLUDE_DIRS ${MKL_CPARDISO_INCLUDE_DIR})
  set(MKL_CPARDISO_LIBRARIES
    ${MKL_CPARDISO_MPI_WRAPPER_LIBRARY}
    ${MKL_CPARDISO_LP64_LIBRARY}
    ${MKL_CPARDISO_SEQ_LIBRARY}
    ${MKL_CPARDISO_CORE_LIBRARY})
endif()

mark_as_advanced(
  MKL_CPARDISO_INCLUDE_DIR
  MKL_CPARDISO_LP64_LIBRARY
  MKL_CPARDISO_SEQ_LIBRARY
  MKL_CPARDISO_CORE_LIBRARY
  MKL_CPARDISO_MPI_WRAPPER_LIBRARY)