# Defines the following variables:
#   - MKL_PARDISO_FOUND
#   - MKL_PARDISO_LIBRARIES
#   - MKL_PARDISO_INCLUDE_DIRS

if(NOT MKL_PARDISO_DIR)
  set(MKL_PARDISO_DIR /usr)
endif()

if(NOT MKL_LIBRARY_DIR)
  set(MKL_LIBRARY_DIR /usr/lib/x86_64-linux-gnu)
endif()

if(NOT MKL_COMPILER_DIR)
  set(MKL_COMPILER_DIR /usr/lib/x86_64-linux-gnu)
endif()

set(MKL_PARDISO_LIBRARY_HINTS
  ${MKL_LIBRARY_DIR}
  ${MKL_PARDISO_DIR}/lib/intel64
  ${MKL_PARDISO_DIR}/lib)

get_filename_component(MKL_ONEAPI_ROOT ${MKL_PARDISO_DIR} DIRECTORY)
set(MKL_PARDISO_COMPILER_HINTS
  ${MKL_COMPILER_DIR}
  ${MKL_ONEAPI_ROOT}/compiler/latest/lib/intel64_lin
  ${MKL_ONEAPI_ROOT}/compiler/latest/lib
  ${MKL_LIBRARY_DIR}
  /usr/lib/x86_64-linux-gnu)

find_path(MKL_PARDISO_INCLUDE_DIR mkl_pardiso.h
  HINTS
    ${MKL_PARDISO_DIR}/include/mkl
    ${MKL_PARDISO_DIR}/include)

find_library(MKL_PARDISO_LP64_LIBRARY NAMES mkl_intel_lp64 mkl_gf_lp64
  HINTS ${MKL_PARDISO_LIBRARY_HINTS})
find_library(MKL_PARDISO_THREAD_LIBRARY NAMES mkl_gnu_thread mkl_intel_thread
  HINTS ${MKL_PARDISO_LIBRARY_HINTS})
find_library(MKL_PARDISO_CORE_LIBRARY NAMES mkl_core
  HINTS ${MKL_PARDISO_LIBRARY_HINTS})
find_library(MKL_PARDISO_OMP_LIBRARY NAMES gomp iomp5
  HINTS ${MKL_PARDISO_COMPILER_HINTS})
find_library(MKL_PARDISO_PTHREAD_LIBRARY NAMES pthread)
find_library(MKL_PARDISO_M_LIBRARY NAMES m)
find_library(MKL_PARDISO_DL_LIBRARY NAMES dl)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(MKL_PARDISO DEFAULT_MSG
  MKL_PARDISO_INCLUDE_DIR
  MKL_PARDISO_LP64_LIBRARY
  MKL_PARDISO_THREAD_LIBRARY
  MKL_PARDISO_CORE_LIBRARY
  MKL_PARDISO_OMP_LIBRARY)

if(MKL_PARDISO_FOUND)
  set(MKL_PARDISO_INCLUDE_DIRS ${MKL_PARDISO_INCLUDE_DIR})
  set(MKL_PARDISO_LIBRARIES
    ${MKL_PARDISO_LP64_LIBRARY}
    ${MKL_PARDISO_THREAD_LIBRARY}
    ${MKL_PARDISO_CORE_LIBRARY}
    ${MKL_PARDISO_OMP_LIBRARY}
    ${MKL_PARDISO_PTHREAD_LIBRARY}
    ${MKL_PARDISO_M_LIBRARY}
    ${MKL_PARDISO_DL_LIBRARY})
endif()

mark_as_advanced(
  MKL_PARDISO_INCLUDE_DIR
  MKL_PARDISO_LP64_LIBRARY
  MKL_PARDISO_THREAD_LIBRARY
  MKL_PARDISO_CORE_LIBRARY
  MKL_PARDISO_OMP_LIBRARY
  MKL_PARDISO_PTHREAD_LIBRARY
  MKL_PARDISO_M_LIBRARY
  MKL_PARDISO_DL_LIBRARY)